services:
  web:
    build:
      context: distvue
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: backend
      args:
        delta_worker_type: ${delta_worker_type}
        duck_worker_type: ${duck_worker_type}
    ports:
      - 8081:8001
    depends_on:
      rabbitmq:
        condition: service_healthy

  deltaworker:
    build:
      context: deltaworker
      args:
        worker_type: ${delta_worker_type}
    deploy:
      mode: replicated
      replicas: ${delta_worker_replicas}
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy

  duckworker:
    build:
      context: duckworker
      args:
        worker_type: ${duck_worker_type}
    deploy:
      mode: replicated
      replicas: ${duck_worker_replicas}
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy
    
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # Management interface
      - "5672:5672"   # RabbitMQ server
    healthcheck: # Healthcheck is required for starting workers
      test: ["CMD", "rabbitmq-diagnostics", "ping", "-q"]
      interval: 30s
      timeout: 10s
      retries: 5


