services:
  web:
    build:
      context: distvue
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: backend
    ports:
      - 8081:8001
    depends_on:
      rabbitmq:
        condition: service_healthy

  deltaworker:
    build:
      context: deltaworker
      dockerfile: Dockerfile_rpc
    ports:
      - 8082:8002
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy

  duckworker:
    build:
      context: duckworker
      dockerfile: Dockerfile_rpc
    ports:
      - 8083:8003
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # Management interface
      - "5672:5672"   # RabbitMQ server
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping", "-q"]
      interval: 10s
      timeout: 10s
      retries: 5


