FROM python:3.9-slim-buster

WORKDIR /usr/src/app

RUN pip install pandas
RUN pip install deltalake
RUN pip install glob2
RUN pip install duckdb==0.9.1
RUN pip install requests
RUN pip install pyarrow
RUN pip install asyncio
RUN pip install sqlparse
RUN pip install aiormq

COPY helpers/ .
COPY rpc/ .

EXPOSE 8003
RUN mkdir data

# Run rpc_server.py when the container launches
CMD ["python", "duck_rpc_server.py"]